# Generated by Django 3.0.6 on 2020-11-06 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_title', models.CharField(max_length=255)),
                ('en_title', models.CharField(blank=True, max_length=255, null=True)),
                ('ar_description', models.TextField(blank=True, null=True)),
                ('en_description', models.TextField(blank=True, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
            ],
            options={
                'verbose_name': 'contest',
                'verbose_name_plural': 'contestes',
                'ordering': ('ar_title', 'en_title'),
            },
        ),
        migrations.CreateModel(
            name='ContestAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_title', models.CharField(max_length=255)),
                ('en_title', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'contest Account',
                'verbose_name_plural': 'contest Sccounts',
                'ordering': ('ar_title', 'en_title'),
            },
        ),
        migrations.CreateModel(
            name='ContestGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_title', models.CharField(max_length=255)),
                ('en_title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'contest Goal',
                'verbose_name_plural': 'contest Goals',
                'ordering': ('ar_title', 'en_title'),
            },
        ),
        migrations.CreateModel(
            name='ContestMesasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True)),
                ('is_required', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.Contest')),
            ],
            options={
                'verbose_name': 'contest Mesasure',
                'verbose_name_plural': 'contest Mesasures',
                'ordering': ('weight',),
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_title', models.CharField(max_length=255)),
                ('en_title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'measure',
                'verbose_name_plural': 'measures',
                'ordering': ('ar_title', 'en_title'),
            },
        ),
        migrations.CreateModel(
            name='ContestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest_mesasure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.ContestMesasure')),
            ],
            options={
                'verbose_name': 'contest Result',
                'verbose_name_plural': 'contest Results',
                'ordering': ('weight',),
            },
        ),
        migrations.CreateModel(
            name='ContestReferral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.Contest')),
            ],
            options={
                'verbose_name': 'contest Referral',
                'verbose_name_plural': 'contest Referrals',
                'ordering': ('weight',),
            },
        ),
        migrations.CreateModel(
            name='Contestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=256)),
                ('rest_name', models.CharField(blank=True, max_length=256, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('avatar', models.CharField(blank=True, max_length=256, unique=True)),
                ('phone', models.CharField(blank=True, max_length=256, unique=True)),
                ('password', models.CharField(blank=True, max_length=256, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Country')),
            ],
            options={
                'verbose_name': 'Contestor',
                'verbose_name_plural': 'Contestors',
                'ordering': ('fname',),
            },
        ),
        migrations.AddField(
            model_name='contestmesasure',
            name='measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.Measure'),
        ),
    ]
